# define the cpu used by the saml21 board
export CPU = saml21
export CPU_MODEL = saml21e18b
export CFLAGS += -D__SAML21E18B__

# include dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

# setup serial terminal
PORT_LINUX ?= /dev/ttyUSB0
include $(RIOTBOARD)/Makefile.include.serial

# this board uses openocd
include $(RIOTBOARD)/Makefile.include.openocd
